### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by mogren** [pahud/amazon-eks-workshop#15]
The links to these two tweets are broken:

## Amazon EKS and Amazon API Gateway Integration

https://twitter.com/pahudnet/status/1030628314044452865

https://twitter.com/pahudnet/status/1030629435664302085

**Comment by pahud** [comment]
Unfortunately, the tweets were deleted by accident. It was Amazon EKS with NodePort service behind internal NLB and API Gateway VPC Link integration. I will re-write a CDK sample for it when I have time. Thanks for the feedback.
