### ISSUE TITLE
cfn template asg security group issue

### ISSUE THREAD

**Issue by shengjhe** [pahud/amazon-eks-workshop#8]
請問有沒有可能在 cfn template 上加入一個 asg  security group 選項，讓cfn 每次建立出來的 worknode 都可以在同一個 security group 群組以方便做防火牆呢？

**Comment by pahud** [comment]
很好的建議，我明天試試看

**Comment by pahud** [comment]
@shengjhe  試試看這個

https://github.com/pahud/eks-templates/issues/17#issuecomment-438998094
